heiseonline/shariff

build/shariff.js
Since IE does not allow spaces in the window name we use „_blank“ as
window name.
See:
http://stackoverflow.com/questions/710756/ie8-var-w-window-open-message-
invalid-argument/1462500#1462500
=> [BUGFIX] Make shariff.js work with IE

src/js/shariff.js
data-backend-url might already contain a query string. Hence it is wrong to always append ?url.
This patch handles the situation properly and adjusts to &url if necessary.
=> [BUGFIX] backendUrl may already have a querystring

src/js/services/twitter.js
URL-String is uri-encoded by url.format (by means of querystring.stringify).
=> Twitter: prevent double encoding with text longer than 120 chars

README-de.md, README.md
Adds the WordPress plugin "Shariff Wrapper" to the list of third party
integrations. It is up to date with Shariff version 1.14.0 and the PHP
backend version 1.5.
=> Add WordPress plugin to third party list

src/js/shariff.js
Fügt den Button-Links die Attribute role=“button“ und aria-label=“title-attribut-des-jeweiligen-dienstes“ hinzu. Dadurch lesen Screen Reader nicht mehr „teilen“ bei fast jedem Button vor, sondern das ausführlichere „Bei Facebook teilen“, „Bei XING teilen“, etc. - natürlich in der jeweiligen Sprache. Auf diese Weise kann beim Einsatz von Screen Readern besser, bzw. überhaupt, zwischen den Buttons unterschieden werden.
=> add attributes for screen readers

src/js/services/pinterest.js
Changes the Pinterest share link from „button“ to „link“ so the Shariff
Button is not replaced with the original button in case the pinit.js is
present.
Fix for https://github.com/heiseonline/shariff/issues/86
=> fix-pinterest-link

package.json
Grunt demo does not start:
$ grunt demo
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "configureProxies:demo" not found. Use --force to continue.
Aborted due to warnings.
The modification of the file "package.json" ("grunt-connect-proxy": "^0.2.0") fixes the problem.
=> modified package.json for grunt demo

src/js/services/pinterest.js
With this little change the image for pinterest will be get from the Open Graph Tag if no data-media-URL is set.
=> get Pinterest Media by Open Graph Tag

src/style/services/googleplus.less
fontawesome updated the google-plus icon and now it's squared and the offset from top should be removed
=> optimized styles for new fa-google-plus icon

src/js/services/diaspora.js
There is an official instance of the share widget that should be used instead.
It is used by the Firefox Share Service ( https://activations.cdn.mozilla.net/de/diaspora.html ) and is hosted on resources belonging to the project itself (more trustworthy / reliable).
=> Changed the diaspora url to the official share url

bower.json
I'm pretty sure this won't break anything and it will prevent quite a few package conflicts.
Also I noticed that jQuery version `^1.11.2` is registered inside the `package.json`, for me this difference makes no seance at all.
=> Allow any 2.x.x jQuery version in bower.json

.jshintrc, CHANGELOG.md, Gruntfile.js, README-de.md, README.md, bower.json, package.json, src/js/dom.js, src/js/services/twitter.js, src/js/shariff.js
motivation: i'd like to use this on a site without jquery and not put the burden of even having to load the bundled jquery bytes just for this little functionallity. we are in 2017, browsers have become good, mobile data volumes (in germany) still suck hard and jquery is overkill for this anyway.
this replaces jquery with a custom (somewhat ugly) shim to save about 240% of file size on non-uglified, uncompressed js.
before: 132945 bytes
after:  38569 bytes
i was not able to integration-test backends, though.
=> replace jquery with vanilla js, save 240% file size

src/js/dom.js
resolves #220.
tested on win7 build 7601 sp1 + ie 11.0.9600.17420
=> support IE11 -- resolves #220

src/js/services/pinterest.js
Issue URL:
https://github.com/heiseonline/shariff/issues/230
Resubmitting because a prior PR was rejected due to build artifacts
https://github.com/heiseonline/shariff/pull/231
The problem was in the file `shariff/src/js/services/pinterest.js`
when no value or an empty string is provided through `data-media-url`, the meta ob:image is supposed to be used as a default.
However, control statement on line 12 is never true
```javascript
if (img && img.length <= 0) {
```
because an empty string is a boolean false, so the code block that pulls out the og:image is never executed.
The statement should be rewritten as follows
```javascript
if (!img || img.length <= 0) {
```
I changed it accordingly.
=> Hotfix for issue 230: Pinterest service can never access og:image

src/js/dom.js
this adds support to use the DOM library introduced in #220 to add `DOMContentLoaded` event listeners:
```js
$(function() {
// code
});
```
this is necessary for code about to be introduced in #213.
=> support dom-ready functions with shariff-native dom library

CHANGELOG.md, Gruntfile.js, README-de.md, README.md, package.json, src/js/shariff.js
Followup to #214 to re-establish the `shariff.complete.js` file.
The js files now contain the content as expected:
- `shariff.complete.js` includes the custom `dom` module
- `shariff.min.js` relies on jQuery to be present
=> resurrect the shariff.complete.js

src/js/shariff.js
When a Tweet is embedded in a page (example below) and shariff is implemented on the same page the script `platform.twitter.com/widgets.js` auomatically opens a second sharing popup when the tweet link is clicked.
This PR checks for the precence of twitters widgets.js and prevents the opening of a second popup.
Example for embedded tweet:
```HTML
<blockquote class="twitter-tweet" data-lang="de"><p lang="en" dir="ltr">Shariff Social Media Buttons (8.x-1.1) released <a href="https://t.co/vaesZ6z0fK">https://t.co/vaesZ6z0fK</a> ! <a href="https://twitter.com/hashtag/shariff?src=hash">#shariff</a> <a href="https://twitter.com/hashtag/d8module?src=hash">#d8module</a> <a href="https://twitter.com/hashtag/d8stable?src=hash">#d8stable</a> <a …
```
=> Fix: Twitter popup opens twice when a tweet is embedded on a page.

src/js/services/mail.js
I am using the TYPO3-extension `rx_shariff` and if i set the attribute `data-mail-body`, it completely replaces the URL which will be inserted automatically if there is no `data-mail-body`-attribute.
But a mail without link does not make any sense, so i would like to replace the placeholder `{url}` with `shariff.getURL()`.
Is this the right place for such modification?
=> Add {url} replacement to mailBody

README-de.md, README.md
Add data-info-url to the table of options, add information about info service to supported services section.
Currently the info service just listed in the options table for the data-services option, but it is nowhere further explained, and the option data-info-url is missing in the options table, too.
Testing: By review.
=> Add missing documentation for info service

README-de.md, README.md, demo/backend.json
After Twitter had discontinued their share count API, the Twitter service has been removed from shariff-backend-php in November 2015, see [https://github.com/heiseonline/shariff-backend-php/pull/48]( https://github.com/heiseonline/shariff-backend-php/pull/48). (Other backends might be maintained less well and so still contain the Twitter service.)
This PR removes references to the Twitter count in documents and removes the twitter service from the backend dummy of the demo.
Beside this, it corrects a typo in the German doc: "... Shariff erzeugt**ze** hingegen Share-Buttons ..."
**How to test:** By review.
Additional note: It might be necessary in near future to do the same for the Google service, because it seems they have also discontinued tracking and counting of plusones and shares in …
=> Remove twitter backend from docs and demo

src/js/shariff.js
Add rel="noopener noreferrer" to the sharing and info hyperlinks if target="_blank".
Hyperlinks with target="_blank" and not having rel="noopener" are both a security and a performance issue, see [https://developers.google.com/web/tools/lighthouse/audits/noopener](https://developers.google.com/web/tools/lighthouse/audits/noopener) for details. The Google site auditing tool "lighthouse" reports this as a security and a performance issue.
For compatibility with older Firefox versions who do not understand the rel="noopener" but the rel="noreferrer", both can be combined to rel="noopener noreferrer", see e.g. [https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ev …
=> Security issue: Add rel="noopener noreferrer" to hyperlinks if target="_blank"

demo/index.html
This PR corrects following 3 issues in the demo main page "demo/index.html":
1. In the parameters listing for the "data-services" parameter of the 2nd example (which is the first one with parameters) one "&amp;quot;" is missing before "whatsapp". See attached screen shot of the [Shariff demo](http://heiseonline.github.io/shariff/).
2. Examples 3, 4 and 5 use the "data-services" parameter, but this is not listed in the parameters listings for these examples.
3. Example 3 does not use the "data-info-url" parameter, but it is shown in the parameters listing for that example.
I have made these 3 changes with 3 commits, so maintainers can decide to cherry-pick some of these 3 changes only, e.g. in case if the 2nd issue is not a mistake but by purpose because only changed parameters compared to …
=> Correct errors in listings of options on the demo page

README-de.md, README.md, src/js/services/info.js, src/js/shariff.js
**Description**
This PR adds a new option infoDisplay (data-info-display) which allows to control how the info page (service = "info") is shown:
- "blank" shows the info page in a new window or browser tab (depending on the browser settings). This is the current behavior.
- "popup" shows the info page in a new small browser window which looks like a dialog, like the sharing links do it now.
- "self" uses the current browser window and tab.
The reason for this PR is that depending on which kind of URL is specified with the data-info-url parameter, different behaviors are most appropriate:
- If the URL is for an external website like the default link to the c't article is, "blank" is the most appropriate.
- If the URL is an internal one, "self" is more appropriate than "blank", and if the …
=> Enhancement: New option infoDisplay (data-info-display) to control display of the info page

README-de.md, README.md, demo/backend.json
In June 2017, Google announced that their Share button will not show any counts anymore in order to speed up loading.
Details see [https://github.com/heiseonline/shariff-backend-php/pull/132](https://github.com/heiseonline/shariff-backend-php/pull/132).
This pull request (PR) here removes the counter for GooglePlus from the demo's dummy backend `backend.json` and changes the readme docs so they don't mention that counter anymore.
In addition, a counter for the new VK service has been added to `backend.json`, and the Facebook counter has been updated to a value greater than zero in `backend.json`.
How to test: Code review for docs, also code review or run the demo for the demo.
=> Remove GooglePlus share count from demo and docs, update demo Facebook counter, add demo VK counter

src/js/services/mail.js
Pull request (PR) for issue #290 .
Handle `data-mail-subject` as described in readme docs:
- If `data-mail-url` is a `mailto:` link and `data-mail-subject` is defined, use value of `data-mail-subject` as mail subject.
- If `data-mail-url` is a `mailto:` link and `data-mail-subject` is not defined, use value of `data-title` or its default as mail subject.
- If `data-mail-url` is **not** a `mailto:` link, don't use the `data-mail-subject` option.
How to test:
1. Code review.
2. Build Shariff with the change of this PR included, or use one of the packages linked below, and test with and without data-mail-subject option.
Packages of Shariff 2.1.2 plus this PR for the 2nd test can be found here:
[https://test5.richard-fath.de/shariff-2.1.2-test-pr291.tar.gz](https://test5.richard-fath.de/sharif …
=> Correct handling of data-mail-subject

src/js/services/reddit.js
Pull request (OR) for issue #292
The normal reddit icon (fa-reddit) is very small and so hard to recognize.
Icon reddit-alien (fa-reddit-alien) is a bit bigger and so the details can be viewn better.
Thanks to @koelling for the hint.
See here the current icon:
And here the one proposed by this PR:
=> Change reddit icon to fa-reddit-alien

README-de.md, README.md, demo/app.less, demo/index.html, src/js/shariff.js, src/style/shariff-layout.less
Pull request (PR) for issue #184 
This PR add a new option `data-button-style` to enable small buttons also on large displays.
The option has 3 possible values:
- `standard` is the default for backwards compatibility and is like without this PR.
- `icon` shows always the icons only, i.e. no counters and no share texts. The special sizing of the `info` icon is unchanged.
- `icon-count` shows icons and share counters, i.e. no share text. The share counters disappear with `data-orientation=horizontal` on very small displays in the same way as with the `standard`setting. The buttons have a fixed width of 80px so they all have the same size, regardless if share counters or not. The special sizing of the `info` icon is unchanged. This button style value of course only makes sense if share …
=> [Enhancement] Add new option data-button-style to enable small buttons

README-de.md
This PR corrects the default services in the options description of README-de.md so it is same as in README.md.
In README.md default services in options description:
> `twitter`, `facebook`, `googleplus`, `info`
= correct.
In README-de.md default services in options description:
> Twitter, Facebook, Google+
Info service missing, names not consistent with README.md.
=> Correct default services in options description of README-de.md

package-lock.json, src/js/services/twitter.js
=> [SECURITY] Handle HTML input to twitter abbreviateText safely 

README-de.md, README.md
I've added the link to the Yellow CMS plugin (https://github.com/schulle4u/yellow-plugin-shariff) into the files README.md and README-de.md.
=> added link to the Yellow CMS plugin

README-de.md, README.md
The previous `shariff-backend-java` seems to be unmaintained. The last commit was in Feb 2015. I took the freedom to change the link to my own `shariff-backend-java`, which is a different implementation, but still active.
=> Change link to Java backend

README-de.md
This pull request adds a space before `info`in the default value for `data-services` in the German readme doc.
It seems the space which was there before has gone with commit [https://github.com/heiseonline/shariff/commit/83738df04c549e3a0d79526ac30b4b10833c1466](https://github.com/heiseonline/shariff/commit/83738df04c549e3a0d79526ac30b4b10833c1466).
=> Add missing space in data-services default value description in German readme doc

package-lock.json, package.json, src/style/shariff-complete.less
This pull request (PR) updates fontawesome free webfonts to the latest version 5.8.1.
It is a requirement for being able to add new services like e.g. [buffer](https://buffer.com/), for which new brand icons have been added recently to fontawesome free.
Since the last update of fontawesome with PR #302 , the structure of the fontawesome npm repository has changed again, so the separate repository for the webfonts has been deprecated, see here: [https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts](https://www.npmjs.com/package/@fortawesome/fontawesome-free-webfonts).
Instead of this, the repository [https://www.npmjs.com/package/@fortawesome/fontawesome-free](https://www.npmjs.com/package/@fortawesome/fontawesome-free) shall be used.
See upgrading information here: …
=> Update fontawesome to version 5.8.1
