README.md, src/js/services/pinterest.js, src/js/shariff.js, src/style/services/pinterest.less, src/style/shariff-services.less
Note, that i've not rebuild the files in `build/`.
=> Add pinterest service

README.md
Add links to implementations for third party systems.
=> [TASK] Add Implementation section

Gruntfile.js
=> Switch to https for CDN

src/js/services/diaspora.js, src/js/shariff.js, src/style/services/diaspora.less, src/style/shariff-services.less
=> add diaspora

src/js/services/stumbleupon.js, src/js/shariff.js, src/style/services/stumbleupon.less, src/style/shariff-services.less
add stumbleupon
check font size
=> +stumbleupon

Gruntfile.js
vll umgeht Github den Fehler irgendwie, aber für meine Testumgebung musste ich den korrigieren.
=> fix demo font-path

src/js/services/diaspora.js, src/js/services/info.js, src/js/services/pinterest.js, src/js/services/qzone.js, src/js/services/reddit.js, src/js/services/stumbleupon.js, src/js/services/tencent-weibo.js, src/js/services/weibo.js, src/js/services/xing.js, src/js/shariff.js, src/style/services/qzone.less, src/style/services/tencent-weibo.less, src/style/services/weibo.less, src/style/shariff-services.less
Hi, I update some localization parts and add support for weibo, tencent-weibo, qzone (mainstreaming social network in China).
=> Add chinese locale and add weibo, tencent-weibo, qzone service

README.md
these statements flow better if the components are reversed.
=> fixed flow

src/js/services/linkedin.js
more control over the title and summary text
=> improved share link to linkedIn

src/js/services/mail.js, src/js/services/twitter.js
=> Add localization supported for the ShareText inside the mail.js and tweet.js

README-de.md
Added a link to a plugin for Kirby CMS
=> Plugin for Kirby CMS

README.md
Added a link to a plugin for Kirby CMS
=> Plugin for Kirby-CMS

src/js/shariff.js
As discussed in #213, this is the separated out PR for the DOM-ready change.
It depends on #226 being merged.
=> Delay sharif initialization until DOM is ready

demo/index.html, src/js/services/print.js, src/js/shariff.js, src/style/services/print.less, src/style/shariff-services.less
Implement print button as a service based on javascript:window.print();
Language keys are still missing.
=> Add print button as a service

README.md
=> Update README.md - added Pagekit extension

README-de.md
=> Update README-de.md - added Pagekit extension

src/style/shariff-layout.less
Code style: Remove trailing white space from line 89 in file shariff-layout.less.
Testing: By review.
=> Code style: Remove trailing white space from shariff-layout.less

README-de.md
Forgotten to translate the description in the options table to German with my previous PR #270 .
Testing: By review.
=> Forgotten to translate to German

README-de.md, README.md, src/js/services/addthis.js, src/js/services/diaspora.js, src/js/services/facebook.js, src/js/services/googleplus.js, src/js/services/info.js, src/js/services/linkedin.js, src/js/services/mail.js, src/js/services/pinterest.js, src/js/services/print.js, src/js/services/qzone.js, src/js/services/reddit.js, src/js/services/stumbleupon.js, src/js/services/telegram.js, src/js/services/tencent-weibo.js, src/js/services/threema.js, src/js/services/tumblr.js, src/js/services/twitter.js, src/js/services/vk.js, src/js/services/weibo.js, src/js/services/whatsapp.js, src/js/services/xing.js
Czech translations added into all .js service files.
=> Added czech translations.

README.md
=> Correct minor typo

src/js/shariff.js, src/style/shariff-layout.less
Pull request (PR) for issue #300 .
This PR changes the class prefix "col-" to "shariff-col-" so it does not interfer anymore with Bootsrap 4.
Depending on your testing environment you can use one of the 2 following methods:
1. Run the shariff demo site locally on a Linux host which has npm installed as described [here in the README.md](https://github.com/heiseonline/shariff#running-demo-site) and check the result with URL=`http://localhost:3000/` in a local browser. This method requires a Linux host which has npm installed.
2. Those who do not have the environment required for method 1 can use modified Shariff packages for the test. Scroll down to Method 2 for the links.
```sh
$ mkdir shariff-test-pr304
$ cd shariff-test-pr304
$ git clone https://github.com/richard67/shariff-plus.git
$ cd …
```
=> [BUGFIX] Change class prefix "col-" to "shariff-col-" for Bootstrap 4 compatibility

src/js/services/reddit.js
This pull request (PR) changes again the icon for reddit as it was done before with PR #293 .
Somehow the change got lost, possibly when merging one of my later PRs because my branches were not up to date, so I guess it was my fault.
=> [REGRESSION] Redo PR #293 - the changes from that merged PR got lost

README-de.md, README.md, demo/index.html, src/js/services/flipboard.js, src/js/services/index.js, src/style/services/flipboard.less, src/style/shariff-services.less
This pull request (PR) adds the Flipboard service to Shariff.
Solution for issue #297 .
It requires PR #302 to be applied for having an icon for the new service.
The reason is that Font Awesome does not have an icon for Flipboard in version 4.
The test also includes the changes from PR #302 , which is a requirement for this PR here.
Depending on your testing environment you can use one of the 2 following methods:
1. Run the shariff demo site locally on a Linux host which has npm installed as described [here in the README.md](https://github.com/heiseonline/shariff#running-demo-site) and check the result with URL=`http://localhost:3000/` in a local browser. This method requires a Linux host which has npm installed.
2. Those who do not have the environment required for method 1 can use …
=> Add new service Flipboard

README-de.md
Please check:
Delete this list before submitting. Pull requests containing the list or failing to check all points will be rejected.
=> Add Magento 2 Integration in README-de.md

README.md
Added Magento 2 Shariff Social Share Extension to list of Third-Party integrations in readme
Please check:
Delete this list before submitting. Pull requests containing the list or failing to check all points will be rejected.
=> Add new Third-Party integration in readme
